apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  superuser: 'admin'
  spassword: 'Saturday_123'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  selector:
    matchLabels:
      app: todo
  replicas: 1
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: pythonwebfsd
    # enter the path to your image, be sure to include the correct region prefix    
        image: sjc.ocir.io/oraclepartnersas/todolist-flask:v3
        ports:
        - containerPort: 5000
      imagePullSecrets:
    # enter the name of the secret you created  
      - name: pythonwebsecret
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 5000
  selector:
    app: todo

---
